### ISSUE TITLE
Move slack bots to BackEnd part

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#1]
Move all slack bots to back-end part architecture scheme

**Comment by OlgaKulikova** [comment]
Все слак-боты являются частью бекенда. На схеме необходимо перенести на сторону бека.

**Comment by OlgaKulikova** [comment]
@danilkuznetsov I this we need a new version of the image with all microservices. Or just use the scheme that was draw by Sasha Baglai.

**Comment by danilkuznetsov** [comment]
I changed main scheme.
