### ISSUE TITLE
Таблица с командами для JuJa - связки.

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#10]
Описание таблицы, которая будет хранить хранителей, и примеров запросов к CRM

**Comment by dtantsev** [comment]
Описал тут:
https://docs.google.com/document/d/16DZ6KxemqTns3UVQKIwx2LwIQVczNgfJ2qKKfSd-J4w/edit?usp=sharing

**Comment by OlgaKulikova** [comment]
@danilkuznetsov Этот вопрос теперь актуален для создания базы данных в микросервисе Team. И выбор базы данных - sql, nosql...

**Comment by starikivan** [comment]
Cвязки будут храниться в team. База - mongoDb. Описание работы с team в соответствующем документе.  Эту задачу наверное надо закрывать.

**Comment by OlgaKulikova** [comment]
Согласна.
