### ISSUE TITLE
Синхронизировать  ТЗ по геймификации

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#12]
Внести фактически сделанные фичи, и отметить их как выполненные, добавить все изменения в  api, обновить документ на github

**Comment by OlgaKulikova** [comment]
@danilkuznetsov Думаю, что уже сейчас стоит все изменения и актуальность проводить только на гитхабе. Дублирование нам помешает. Есть отдельные задачи по ТЗ Gamification. По их выполнению надо будет сделать контрольный чек по этой ТЗ.

**Comment by danilkuznetsov** [comment]
@OlgaKulikova 
я предлагал сделать финальный чек и полностью перейти на ведение на github.
Для этого проверить все ли перенесли со сторой доки + актуальность текущего состояния. 
после чего про старую доку можно забыть

**Comment by OlgaKulikova** [comment]
@danilkuznetsov As I see this task is done?

**Comment by OlgaKulikova** [comment]
I see in this Technical Requirements some extra info. E.g. GMF-F3, String "ссылка на старый документ до переноса". Keepers thanks endpoint also has to be changed (needed to be discussed).

**Comment by danilkuznetsov** [comment]
I removed some extra old  info
I think, We need to discuss about  GMF-F6 and GMF-F7 in new task
