### ISSUE TITLE
Принять решение по дальнейшей судьбе user сервиса

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#14]

**Comment by OlgaKulikova** [comment]
Предложение:

**Comment by danilkuznetsov** [comment]
@OlgaKulikova 
Привет,
1. Согласен
2. Для первого запуска нам не нужны киперы, мы пока обходимся без них + в наших планах вообще уйти от этой сущности в crm. Поэтому думаю нет смысла поддерживать и дорабатывать этот метод. 
Мне кажется, что потом придется больше удалять

**Comment by OlgaKulikova** [comment]
@danilkuznetsov Ты немного не так ответил, как я бы хотела)))
пункт 2 - не касается киперов. А касается того, чтобы создать отдельную DB для всего юзер сервиса.

По киперам еще раз проговорю - метод уже реализован. Вопрос в том - надо удалять, или пусть пока висит, удалим со след. релизом?

**Comment by danilkuznetsov** [comment]
Решение приняли.

Делаем новые сервисы, фичи по кипеерам пока находяться в замороженном состоянии. 
После разработки сервисов, продолжим переделку и доработку нужного функционала
