### ISSUE TITLE
Создать модули-заготовки для микросервисов Keepers и Team

### ISSUE THREAD

**Issue by OlgaKulikova** [JujaLabs/docs#17]

**Comment by OlgaKulikova** [comment]
Keepers done!

**Comment by OlgaKulikova** [comment]
Teams done!
Осталось сделать KeeperAdminSlackBot

**Comment by OlgaKulikova** [comment]
@VadimDyachenko по этой задаче осталось тебе - KeeperAdminSlackBot

**Comment by OlgaKulikova** [comment]
Update!
Необходимо еще создать Keepers-slackbot и Teams-slackbot

**Comment by OlgaKulikova** [comment]
Up! Teams-slackbot is left.

**Comment by starikivan** [comment]
Teams-slackbot is done
