### ISSUE TITLE
Добавить в документацию API Gamification описание ачивки Welcome

### ISSUE THREAD

**Issue by VadimDyachenko** [JujaLabs/docs#18]

**Comment by OlgaKulikova** [comment]
@VadimDyachenko Это сделано?

**Comment by VadimDyachenko** [comment]
Да, ачивка GMF-F9.  Только я не могу вспомнить почему данил вернул в In Progress. Чего тут не хватает?

**Comment by danilkuznetsov** [comment]
я тоже не помню, поэтому закрыл :)
