### ISSUE TITLE
Перенести список полезных линков в wiki

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#25]
Список полезных линков из старой доки перенести в wiki

Можно перенести все старые записи митингов и прочую инфу

**Comment by OlgaKulikova** [comment]
Подумала о том, что в гугл-доке удобно отмечать ребятам, кто что уже прочитал-просмотрел. А в Вики это не так удобно делать.

**Comment by danilkuznetsov** [comment]
надо подумать над этим вопросом, дублирование плохо :(

**Comment by OlgaKulikova** [comment]
как вариант, ссылки (полезные на наши ресурсы), видео с наших митингов - хранить в гитхаб вики. А просто интересные ссылки на  прочтение, просмотр по разным темам - в гугл доке (в ней отмечать кто что прочел-просмотрел) и на нее дать ссылку в вики.

**Comment by OlgaKulikova** [comment]
@danilkuznetsov I need your approve.

**Comment by danilkuznetsov** [comment]
@OlgaKulikova 
Yes, I approve. Great solution.
