### ISSUE TITLE
Принять решение про префиксам для формирования url

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#28]
Выработать политику создания url, добавить возможность указывать версию api

**Comment by OlgaKulikova** [comment]
Предлагаю на каждый микросервис "/api/<serviceName>. Внутри микросервиса не должно повторяться <serviceName>.
По поводу версионности api - надо еще подробней изучить вопрос, как реализовывать.

**Comment by OlgaKulikova** [comment]
UP!

**Comment by OlgaKulikova** [comment]
Gamification - `/gamification/v1/...`
Users - `/users/v1/...`
Keepers - `/keepers/v1/...`
Teams - `/teams/v1/...`
Что делать с версионностью в слак ботах? Помоему там нельзя начинать с чего-то еще, кроме `/commands/...`, или как? у нас выходит, что в слак ботах нет <service name> в url. 
@danilkuznetsov  - твое мнение?

**Comment by OlgaKulikova** [comment]
Done!
