### ISSUE TITLE
Добавить правило по кол-ву тестов в workflow

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#4]
приняли решение: обязательно unit на все критичные случаи integration на все endpoint acceptance.

**Comment by VadimDyachenko** [comment]
Подредактировал доку workflow

**Comment by OlgaKulikova** [comment]
@VadimDyachenko а где она?))) она есть на гитхаб? если нет - давай ее в Wiki перенесем.

**Comment by VadimDyachenko** [comment]
Я внес изменения в файл гугл доки. Петр сделал PR #3 Move workflow description, в котором эти изменения включил. Эту таску можно закрывать.
