### ISSUE TITLE
Discuss about GMF-F6

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#40]
Doc for [GMF-F6](https://github.com/JujaLabs/docs/tree/master/architecture/gamification#gmf-f6)

**Comment by OlgaKulikova** [comment]
Реализовали раздачу ачивок Хранителям по крону раз в неделю, а также дополнительно реализован эндпоинт в Gamification для ручной раздачи этих же ачивок (в случае, если в Системе будет сбой).
