### ISSUE TITLE
Таблица Хранителей в CRM

### ISSUE THREAD

**Issue by danilkuznetsov** [JujaLabs/docs#7]
Описание таблицы, которая будет хранить хранителей, и примеров запросов к CRM

**Comment by danilkuznetsov** [comment]
@dtantsev Напиши в каком нибудь варианте, я потом добавлю в доку, или можешь сразу прислать pr в нужный файл в этом репозитории  ;)

**Comment by dtantsev** [comment]
Описал тут:
https://docs.google.com/document/d/16DZ6KxemqTns3UVQKIwx2LwIQVczNgfJ2qKKfSd-J4w/edit?usp=sharing

**Comment by OlgaKulikova** [comment]
добавила в пакет user файл CRMRequests
